home:
    path: /
    controller: App\Controller\HomeController::index   
    
admin:
    path: /admin
    controller: App\Controller\AdminController::index  

news:
    path: /news
    controller: App\Controller\NewsController::list      
    
news_single:
    path: /news/{id}
    controller: App\Controller\NewsController::single     